settings:
  title: 'Estado del sitio CODIG.EC'
  url: 'https://status.codig.ec' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: www-codig-ec
    name: www.codig.ec
    description: 'Built for anything connected to the Internet.'
    url: 'https://codig.ec'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: terminos-codig-ec
    name: terminos.codig.ec
    url: 'https://terminos.codig.ec'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: codig-bk-pro
    name: codig-bk-pro.codig.ec
    url: 'https://codig-bk-pro.codig.ec/param/api/v1'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: home-codig-ec
    name: home.codig.ec
    url: 'https://home.codig.ec'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
